# Generated by Django 4.0.1 on 2022-01-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='total_booked_seats',
        ),
    ]
