# Generated by Django 4.0.1 on 2022-01-18 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0002_remove_show_total_booked_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
