# Generated by Django 4.0.1 on 2022-01-18 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0002_remove_show_total_booked_seats'),
        ('order', '0002_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='show',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='theatre.show'),
            preserve_default=False,
        ),
    ]
